
on:
  watch:
  # test
    run : echo Hello, World! Today is %m-%d-%Y %H:%M:%S
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - edited
  # schedule:
    # - cron : '* * /1 * *'
